name: Participant Gathering

on:
  # Gathers all of the participants for pull requests to assist in giving proper credit.
  pull_request:

jobs:
  pull_request_participants:
    name: Gather pull request participants
    runs-on: ubuntu-latest
    timeout-minutes: 20

    #
    steps:
      - name: Fetch pull request data
        uses: actions/github-script@e3cbab99d3a9b271e1b79fc96d103a4a5534998c # v5.1.0
        with:
          script: |
            const pr_participants = [];

            const pr_comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }},
            });

            console.debug( pr_comments );

            if ( pr_comments instanceof Array) {
              console.log( 'type array' );
            } else if ( typeof pr_comments  == "object" ) {
              console.log( 'type object' );
            }

            console.debug( pr_participants );

            pr_comments.data.forEach( function( element, index, array ) {
              pr_participants.push( element.user.login );
            });

            console.debug( pr_participants );
