name: Participant Gathering

on:
  # Gathers all of the participants for pull requests to assist in giving proper credit.
  pull_request:

jobs:
  pull_request_participants:
    name: Gather pull request participants
    runs-on: ubuntu-latest
    timeout-minutes: 20

    #
    steps:
      - name: GraphQL
        uses: actions/github-script@e3cbab99d3a9b271e1b79fc96d103a4a5534998c # v5.1.0
        continue-on-error: ${{ true }}
        id: contributor-data
        with:
          script: |
            const script = require('tools/contributions.js');

      - name: Test data
        run: echo "${{steps.contributor-data.outputs.result}}"

      # Fetches all issues linked to the pull request.
      - name: Fetch linked issues
        uses: kin/gh-action-get-linked-issues@8ef8d85f1410531f5adadb30609d92cda2c8a650 # v2.0
        id: linked-issues

      - name: Print linked issue numbers
        run: echo ${{ steps.linked-issues.outputs.issues }}
