name: Participant Gathering

on:
  # Gathers all of the participants for pull requests to assist in giving proper credit.
  pull_request:

jobs:
  pull_request_participants:
    name: Gather pull request participants
    runs-on: ubuntu-latest
    timeout-minutes: 20

    #
    steps:
      # Fetches all commit authors for the pull request.
      - name: Fetch pull request commits
        uses: actions/github-script@e3cbab99d3a9b271e1b79fc96d103a4a5534998c # v5.1.0
        with:
          script: |
            const pr_committers = [];

            const pr_commits = await github.rest.pulls.listCommits({
              owner: 'WordPress',
              repo: 'gutenberg',
              pull_number: 38187,
            });

            pr_commits.data.forEach( function( element, index, array ) {
              // Log both author and committer if they are different.
              let committer = '';
              let author = '';

              if ( null != element.committer ) {
                if ( null != element.committer.login ) {
                  committer = element.committer.login;
                } else {
                  // Do we really want to format this way?
                  committer = element.committer.name + ' <' element.committer.email + '>';
                }
              }

              if ( null != element.author ) {
                if ( null != element.author.login ) {
                  author = element.author.login;
                } else {
                  // Do we really want to format this way?
                  author = element.author.name + ' <' element.author.email + '>';
                }
              }

              pr_committers.push( committer );

              if ( author != committer ) {
                pr_comitters.push( author );
              }
            });

            console.debug( pr_committers );

            return JSON.stringify( pr_committers );

      # Fetches all pull request commenters.
      - name: Fetch pull request commenters
        uses: actions/github-script@e3cbab99d3a9b271e1b79fc96d103a4a5534998c # v5.1.0
        with:
          script: |
            const pr_commenters = [];

            const pr_comments = await github.rest.issues.listComments({
              owner: 'WordPress',
              repo: 'gutenberg',
              issue_number: 38362,
            });

            pr_comments.data.forEach( function( element, index, array ) {
              pr_commenters.push( element.user.login );
            });

            console.debug( pr_commenters );
            console.debug( ${{ toJSON( github.event.pull_request ) }} );

            return JSON.stringify( pr_commenters );

      # Fetches all contributors engaged in pull request reviews.
      - name: Fetch pull request reviewer discussions
        uses: actions/github-script@e3cbab99d3a9b271e1b79fc96d103a4a5534998c # v5.1.0
        with:
          script: |
            const pr_reviewers = [];

            const pr_review_comments = await github.rest.pulls.listReviewComments({
              owner: 'WordPress',
              repo: 'gutenberg',
              pull_number: 38362,
            });

            pr_review_comments.data.forEach( function( element, index, array ) {
              pr_reviewers.push( element.user.login );
            });
            console.debug( pr_reviewers );

            return JSON.stringify( pr_reviewers );

      # Fetches all issues linked to the pull request.
      - name: Fetch linked issues
        uses: kin/gh-action-get-linked-issues@8ef8d85f1410531f5adadb30609d92cda2c8a650 # v2.0
        id: linked-issues

      - name: Print linked issue numbers
        run: echo ${{ steps.linked-issues.outputs.issues }}
